bbs/config/routes.rb
Rails.application.routes.draw do
  root 'my_threads#index'

  resources :my_threads do
    resources :comments, only: [:create, :destroy, :edit, :show, :new, :update]
  end

end

bbs/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :my_thread
end

bbs/app/models/my_thread.rb
class MyThread < ActiveRecord::Base
  has_many :comments
end

bbs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bbs/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @my_thread = params[:my_thread_id]
  end

  # GET /comments/1/edit
  def edit
    @my_thread = MyThread.find(params[:my_thread_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @my_thread = params[:my_thread_id]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to my_thread_path(@my_thread), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @my_thread = params[:my_thread_id]
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to my_thread_path(@my_thread), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @my_thread = params[:my_thread_id]
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to my_thread_path(@my_thread), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:my_thread_id, :content)
    end
end

bbs/app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only: [:show, :edit, :update, :destroy]

  # GET /my_threads
  # GET /my_threads.json
  def index
    @my_threads = MyThread.all
  end

  # GET /my_threads/1
  # GET /my_threads/1.json
  def show
    @comments = Comment.where(my_thread_id: params[:id])
  end

  # GET /my_threads/new
  def new
    @my_thread = MyThread.new
  end

  # GET /my_threads/1/edit
  def edit
  end

  # POST /my_threads
  # POST /my_threads.json
  def create
    @my_thread = MyThread.new(my_thread_params)

    respond_to do |format|
      if @my_thread.save
        format.html { redirect_to @my_thread, notice: 'My thread was successfully created.' }
        format.json { render :show, status: :created, location: @my_thread }
      else
        format.html { render :new }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_threads/1
  # PATCH/PUT /my_threads/1.json
  def update
    respond_to do |format|
      if @my_thread.update(my_thread_params)
        format.html { redirect_to my_thread_path(@my_thread.id), notice: 'My thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_thread }
      else
        format.html { render :edit }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_threads/1
  # DELETE /my_threads/1.json
  def destroy
    binding.pry
    @my_thread.destroy
    respond_to do |format|
      format.html { redirect_to my_threads_path notice: 'My thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_thread
      @my_thread = MyThread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_thread_params
      params.require(:my_thread).permit(:title, :content)
    end
end

bbs/app/helpers/application_helper.rb
module ApplicationHelper
end

bbs/app/helpers/comments_helper.rb
module CommentsHelper
end

bbs/app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

bbs/app/views/comments/_form.html.erb
<%= form_for([@my_thread, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>

  <div class="hidden">
    <%= f.hidden_field :my_thread_id, value: @my_thread.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bbs/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', my_thread_path(@my_thread.id) %>

bbs/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>My thread</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.my_thread %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

bbs/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', my_thread_path(@my_thread) %>

bbs/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My thread:</strong>
  <%= @comment.my_thread %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

bbs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bbs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

bbs/app/views/my_threads/_comments.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>My thread:</strong>
  <%= @comment.my_thread %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

bbs/app/views/my_threads/_form.html.erb
<%= form_for(@my_thread) do |f| %>
  <% if @my_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_thread.errors.count, "error") %> prohibited this my_thread from being saved:</h2>

      <ul>
      <% @my_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bbs/app/views/my_threads/edit.html.erb
<h1>Editing My Thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_thread %> |
<%= link_to 'Back', my_threads_path %>

bbs/app/views/my_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing My Threads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_threads.each do |my_thread| %>
      <tr>
        <td><%= my_thread.title %></td>
        <td><%= my_thread.content %></td>
        <td><%= link_to 'Show', my_thread %></td>
        <td><%= link_to 'Edit', edit_my_thread_path(my_thread) %></td>
        <td><%= link_to 'Destroy', my_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My thread', new_my_thread_path %>

bbs/app/views/my_threads/new.html.erb
<h1>New My Thread</h1>

<%= render 'form' %>

<%= link_to 'Back', my_threads_path %>

bbs/app/views/my_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @my_thread.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @my_thread.content %>
</p>

<p>
  <strong>Comment:</strong>
  <br>
  <% @comments.each do |comment| %>
  <%= comment.content %>
  <%= link_to 'Edit', edit_my_thread_comment_path(comment.my_thread_id,comment.id) %>
  <%= link_to 'Destroy', my_thread_comment_path(comment.my_thread_id,comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>

  <br>
  <% end %>
</p>

<%= link_to "Create comment", new_my_thread_comment_path(@my_thread) %>
<%= link_to 'Edit', edit_my_thread_path(@my_thread) %>
<%= link_to 'Back', my_threads_path %>